<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Orders.aspx.cs" Inherits="Orders" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Panel ID="OrdersPanel" runat="server" style="overflow: auto;" Width="1037px">
                <asp:GridView ID="GridView1" runat="server" DataSourceID="OrdersSqlDataSource" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" DataKeyNames="OrderID" AllowPaging="True">
                    <Columns>
                        <asp:BoundField DataField="OrderID" HeaderText="OrderID" InsertVisible="False" ReadOnly="True" SortExpression="OrderID" />
                        <asp:BoundField DataField="CustomerID" HeaderText="CustomerID" SortExpression="CustomerID" />
                        <asp:BoundField DataField="DeliveryType" HeaderText="DeliveryType" SortExpression="DeliveryType" />
                        <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                        <asp:BoundField DataField="OrderDate" HeaderText="OrderDate" SortExpression="OrderDate" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="OrdersSqlDataSource" runat="server" ConnectionString='<%$ ConnectionStrings:OrdersDatabaseConnectionString %>' SelectCommand="SELECT * FROM [Orders]"></asp:SqlDataSource>
            </asp:Panel>
        </div>
    </form>
</body>
</html>
